# Generated by Django 4.1.5 on 2023-05-24 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="login_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.IntegerField()),
                ("user_mail", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(9999999999)
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("discription", models.CharField(max_length=5000)),
                ("url", models.URLField(max_length=100)),
                ("video_in", models.CharField(max_length=2)),
                ("tags", models.CharField(max_length=500)),
            ],
        ),
    ]
