# Generated by Django 4.1.5 on 2023-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_data", "0002_login_user_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="video_in",
            field=models.CharField(max_length=10),
        ),
    ]
