# Generated by Django 4.1.5 on 2023-05-26 10:41

import app_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_data", "0003_alter_upload_video_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="image",
            field=models.ImageField(null=True, upload_to=app_data.models.getFileName),
        ),
    ]
