# Generated by Django 4.1.5 on 2023-05-26 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_data", "0004_upload_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="uid",
            field=models.IntegerField(
                null=True,
                validators=[django.core.validators.MaxValueValidator(9999999999)],
            ),
        ),
    ]
