# Generated by Django 4.1.5 on 2023-05-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_data", "0005_alter_upload_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="videos",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_data.registration",
            ),
        ),
    ]
