# Generated by Django 4.1.5 on 2023-05-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_data", "0006_upload_videos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upload",
            name="videos",
        ),
    ]
