# Generated by Django 4.1.5 on 2023-05-30 10:51

import app_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_data", "0007_remove_upload_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="profile",
            field=models.ImageField(
                null=True, upload_to=app_data.models.getFileNameProfile
            ),
        ),
    ]
