# Generated by Django 4.1.5 on 2023-05-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_data", "0008_registration_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="upload",
            old_name="discription",
            new_name="description",
        ),
    ]
