# Generated by Django 4.1.5 on 2023-05-31 09:34

import app_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_data", "0009_rename_discription_upload_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="filtertable",
            fields=[
                ("id", models.IntegerField()),
                ("name", models.CharField(max_length=30)),
                ("profile", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=5000)),
                ("url", models.URLField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="registration",
            name="profile",
            field=models.ImageField(
                default="default-avatar.jpg",
                null=True,
                upload_to=app_data.models.getFileNameProfile,
            ),
        ),
    ]
