# Generated by Django 4.1.5 on 2023-05-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_data", "0010_filtertable_alter_registration_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="filtertable",
        ),
    ]
