# Generated by Django 4.1.5 on 2023-06-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_data", "0012_alter_registration_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="description",
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="upload",
            name="video_in",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")], max_length=10
            ),
        ),
    ]
