# Generated by Django 4.1.5 on 2023-06-08 05:29

import app_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_data", "0013_alter_upload_description_alter_upload_video_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="description",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="upload",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=app_data.models.getFileName
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="tags",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
