# Generated by Django 4.1.5 on 2023-06-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_data", "0017_alter_registration_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="upload",
            name="category",
            field=models.CharField(
                choices=[
                    ("gaming", "Gaming"),
                    ("education", "Education"),
                    ("music", "Music"),
                    ("sports", "Sports"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
