# Generated by Django 4.1.5 on 2023-06-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_data", "0018_alter_registration_name_alter_upload_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="category",
            field=models.CharField(
                choices=[
                    ("gaming", "Gaming"),
                    ("education", "Education"),
                    ("music", "Music"),
                    ("sports", "Sports"),
                    ("education", "Education"),
                    ("fashion & style", "Fashion & Style"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
